# Use a Node.js base image
FROM node:18

RUN apt-get update && apt-get install -y ffmpeg


# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

RUN npm install -g nodemon

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["nodemon", "server.js"]
